name: FSRCNN_FastMRI
seed: 1234
track: &track True
script_path: /home/nvidia/Projects/Expe/FastMRI/SRFastMRI
scaling_factor: &scaling_factor 2
model:
  class_name: FSRCNN
  module_name: src.models.super_resolution
  parameters:
    scale_factor: *scaling_factor
    d: 56
    s: 12
    m: 4

dataloader:
  class_name: SRKneeMRILoader
  module_name: src.data.loaders.kneeMRI
  parameters:
    train_data_dir: /home/nvidia/Projects/Datasets/fastmri/singlecoil_train/
    val_data_dir: /home/nvidia/Projects/Datasets/fastmri/singlecoil_val/
    lr_image_scale: *scaling_factor
    batch_size: 16
    num_workers: 8
    debug: False

trainer:
  class_name: SRTrainer
  module_name: tasks.SR.trainer
  parameters:
    num_epochs: 25
    early_stopping_patience: 5
    lr_scheduler: plateau
    lr: 0.00001
    weight_decay: 0.0
    track: *track
    loss:
      class_name: EPFLoss
      module_name: src.optimisation.losses
      parameters:
          lambda_1: 0.7
          lambda_2: 0.3
          lambda_3: 1
    metric:
      - module_name: torchmetrics.image
        class_name: PeakSignalNoiseRatio
        parameters:

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
