name: SRRESUNET_L1
seed: 1234
track: &track True
script_path: /home/nvidia/Projects/Expe/FastMRI/SRFastMRI
scaling_factor: &scaling_factor 2
model:
  class_name: SRResUNet
  module_name: src.models.super_resolution
  parameters:
dataloader:
  class_name: SRKneeMRILoader
  module_name: src.data.loaders.kneeMRI
  parameters:
    train_data_dir: /Users/bniepce/Projects/Datasets/fastMRI/knee_singlecoil_val/
    val_data_dir: /Users/bniepce/Projects/Datasets/fastMRI/knee_singlecoil_val/
    lr_image_scale: *scaling_factor
    low_pass_radius: 30.
    target_snr: 20.
    batch_size: 2
    num_workers: 4
    debug: True

trainer:
  class_name: SRTrainer
  module_name: tasks.SR.trainer
  parameters:
    num_epochs: 2
    early_stopping_patience: 5
    lr_scheduler: plateau
    lr: 0.00002
    weight_decay: 0.00001
    track: *track
    loss:
      class_name: L1Loss
      module_name: torch.nn
      parameters:
    metric:
      - module_name: torchmetrics.image
        class_name: PeakSignalNoiseRatio
        parameters:

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
