export_path: './exports'
model_path: './logs/EDSR_FastMRI_7f83/best_model.pth'
model_input_size: !!python/tuple [128, 128]
quantization_dataset:
  module_name: src.data.sets.super_resolution
  class_name: FastMRISuperResolutionDataReader
  parameters:
    data_folder: /home/nvidia/Projects/Datasets/fastmri/singlecoil_val/
    num_samples: 100
model:
  class_name: EDSR
  module_name: src.models.super_resolution
  parameters:
    in_channels: 1
    scale_factor: 2
    num_blocks: 32
    num_feats: 256
