name: FSRCNN_FastMRI
seed: 1234
track: &track True
script_path: /Users/bniepce/Projects/Research/MRI/SRFastMRI/
scaling_factor: &scaling_factor 2
model:
  class_name: FSRCNN
  module_name: src.models.super_resolution
  parameters:
    scale_factor: *scaling_factor
    d: 64
    s: 16
    m: 4

dataloader:
  class_name: SRKneeMRILoader
  module_name: src.data.loaders.kneeMRI
  parameters:
    train_data_dir: /home/nvidia/Projects/Datasets/fastmri/singlecoil_train/
    val_data_dir: /home/nvidia/Projects/Datasets/fastmri/singlecoil_val/
    lr_image_scale: *scaling_factor
    batch_size: 16
    num_workers: 8
    debug: False

trainer:
  class_name: FSRCNNTrainer
  module_name: tasks.FSRCNN.trainer
  parameters:
    num_epochs: 50
    early_stopping_patience: 5
    lr_scheduler: plateau
    lr: 0.0001
    weight_decay: 0.
    track: *track
    loss:
      module_name: src.optimisation.losses
      class_name: SRLoss
      parameters:
    metric:
      - module_name: torchmetrics.image
        class_name: PeakSignalNoiseRatio
        parameters:

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
