name: RealESRGAN_FastMRI
seed: 1234
track: &track True
script_path: /home/nvidia/Projects/Expe/FastMRI/SRFastMRI
scaling_factor: &scaling_factor 2
model:
  class_name: RealESRGAN
  module_name: src.models.super_resolution
  parameters:
    in_channels: 1
    out_channels: 1
    num_features: 48
    num_blocks: 16
    upscale_factor: *scaling_factor

dataloader:
  class_name: SRKneeMRILoader
  module_name: src.data.loaders.kneeMRI
  parameters:
    train_data_dir: /home/nvidia/Projects/Datasets/fastmri/singlecoil_train/
    val_data_dir: /home/nvidia/Projects/Datasets/fastmri/singlecoil_val/
    lr_image_scale: *scaling_factor
    batch_size: 8
    num_workers: 8
    debug: False

trainer:
  class_name: SRTrainer
  module_name: tasks.SR.trainer
  parameters:
    num_epochs: 50
    early_stopping_patience: 10
    lr_scheduler: plateau
    lr: 0.00002
    weight_decay: 0.00001
    track: *track
    loss:
      module_name: src.optimisation.losses
      class_name: L1MSSIMLoss
      parameters:
        alpha: 0.84
    metric:
      - module_name: torchmetrics.image
        class_name: PeakSignalNoiseRatio
        parameters:

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
